# Generated by Django 5.2 on 2025-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
