# Generated by Django 5.2 on 2025-05-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera_app', '0005_scanhistory_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
