# Generated by Django 5.2 on 2025-05-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera_app', '0008_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
