# Generated by Django 5.2 on 2025-05-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera_app', '0010_remove_transaction_points_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='points_used',
        ),
        migrations.AddField(
            model_name='transaction',
            name='points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
