# Generated by Django 5.2 on 2025-05-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera_app', '0011_remove_scanhistory_points_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
